### ISSUE TITLE
"Basic usage" does not work 

### ISSUE THREAD

**Issue by Gobmichet** [nizarmah/calendar-javascript-lib#17] opened 2019-08-29 06:41 UTC
Hi,
Just trying the basic config/usage on the home page in order to test the lib and it doesn't work.

1/ the "basic config" code is missing a ',' in calendar creation and a '}' in data creation.

2/ when i do correct this and launch the code here is what i get in the console : 
```
Uncaught TypeError: Cannot read property 'appendChild' of null
    at Calendar.draw (calendarorganizer.min.js:1)
    at new Calendar (calendarorganizer.min.js:1)
    at calendar:15
```

Since i use the min.js as recommanded it will be difficult to give more infos, i'll try replacing the min.js by a non minified version and investigate but since you wrote the lib, do you have any idea on what's going on ?

Thanks in advance,

**Comment by nizarmah** [comment] 2019-08-29 07:42
Hey! I'm looking into it right now. I think the documentation is wrong. You are right regarding those parenthesis and braces. However, I think there is more in the configuration that was not written correctly. I'll look into it right now. In the meantime, please check `examples` in the repository and use that sample code, kindly.
Let me know what happens, and I'll update you with what the issue is.

**Comment by nizarmah** [comment] 2019-08-29 07:46
Alright, I figured out the issue.

So, after doing the fixes that you suggested and switching to the not minified version of the file, it indicated that `document.findElementById(this.id)` for the calendar was not working. 

Apparently, the documentation is missing some HTML tags.

```html
<div id="calendarContainer"></div>
<div id="organizerContainer"></div>
```

The documentation is missing the HTML Div containers for both the Calendar and the Organizer. Once you add them, the issue should be closed. However, I'll fix the documentation, push, then close this issue.

**Closed as completed** 2019-08-29 07:50 UTC

**Comment by Gobmichet** [comment] 2019-08-29 08:25
Thanks ^^
